---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  RootKey:
    Type: "AWS::KMS::Key"
    Properties:
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Action: "kms:*"
          Principal:
            AWS: "arn:aws:iam::123456789012:user/Test"
          Resource: "*"
