name: cfn_model

on:
  push:
    branches:
      - master

jobs:
  commit:
    name: Commit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Install Bundler
      run: gem install bundler
    - name: Which bundler?
      run: bundle -v
    - name: Bundle install
      run: bundle check || bundle install
    #- name: Rubocop lint
    #  run: bundle exec rubocop -D
    - name: Rspec tests
      run: bundle exec rspec --require spec_helper spec

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: commit
    steps:
      # is this the same commit hash we saw in commit?
      - uses: actions/checkout@v2
      - run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git fetch --prune --unshallow
      - name: Set up Ruby 2.5
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - name: Publish to RubyGems
        run: bash ./publish.sh
        env:
          rubygems_api_key: ${{secrets.rubygems_api_key}}
